### ISSUE TITLE
插件默认分类没有正确归类到“功能”中

### ISSUE THREAD

**Issue by wlz-remake** [xipesoy/zhenxun_plugin_meiriyiju#1]
看了一下是真寻的设置中没有分类的功能才会被归类到“功能”分类中，如果主动添加“功能”分类的话会被独立归到另一个“功能”分类
![image](https://user-images.githubusercontent.com/105090141/176398599-8811eaae-5db5-43d8-bfa5-97cfeb4f08d6.png)
删除__init__.py中的__plugin_type__就好啦

**Comment by xipesoy** [comment]
嗯嗯
